repos:
- repo: https://github.com/astral-sh/uv-pre-commit
  rev: 0.7.6
  hooks:
    - id: uv-lock
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml
    -   id: check-added-large-files
-   repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
    -   id: black
-   repo: https://github.com/iterative/dvc
    rev: 3.60.1
    hooks:
    -   id: dvc-pre-commit
        additional_dependencies: ["dvc[s3]"]
    -   id: dvc-pre-push
        additional_dependencies: ["dvc[s3]"]
    -   id: dvc-post-checkout
        stages: [post-checkout]
        always_run: true
        additional_dependencies: ["dvc[s3]"]
