services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: churn-prediction-api
    container_name: churn-prediction-api
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: unless-stopped
