stages:
  data_collection:
    cmd: uv run python -m src.data_collection
    deps:
    - src/config.py
    - src/data_collection.py
    - src/logs.py
    outs:
    - artifacts/data/raw
  data_cleaning:
    cmd: uv run python -m src.data_cleaning
    deps:
    - artifacts/data/raw
    - src/config.py
    - src/data_cleaning.py
    - src/logs.py
    outs:
    - artifacts/data/processed
  data_split:
    cmd: uv run python -m src.data_split
    deps:
    - artifacts/data/processed
    - src/config.py
    - src/data_split.py
    - src/logs.py
    outs:
    - artifacts/data/split
  feature_engineering:
    cmd: uv run python -m src.feature_engineering
    deps:
    - artifacts/data/split
    - src/config.py
    - src/feature_engineering.py
    - src/logs.py
    outs:
    - artifacts/data/features
  model_training:
    cmd: uv run python -m src.model_training
    deps:
    - artifacts/data/features
    - src/config.py
    - src/logs.py
    - src/model_training.py
    - params.yaml
