name: CI

on: [push, pull_request]

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    container: ghcr.io/astral-sh/uv:0.7.6-python3.11-bookworm-slim
    steps:
      - name: Install Git
        run: apt-get update && apt-get install -y git

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: uv sync --dev

      - name: Lint with ruff
        run: uv run ruff check .

      - name: Run tests
        run: uv run pytest
